/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Clases.BebidasClase;
import Clases.ClasePostres;
import Clases.ComidaClase;

/**
 *
 * @author Carlos Gonzalez
 */
public class Pagar extends javax.swing.JFrame {
     ComidaClase comidaclase;
     ClasePostres clasepostres;
     BebidasClase bebidasclase;
    /**
     * Creates new form Pagar
     */
     
    public Pagar(ComidaClase comidaClase, ClasePostres clasepostres, BebidasClase bebidasClase) {
        this.comidaclase = comidaClase;
        this.clasepostres = clasepostres;
        this.bebidasclase = bebidasClase;
        initComponents();
    }

    public Pagar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnMostrarCuenta = new javax.swing.JButton();
        LabelCuentaTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cuenta Total");

        BtnMostrarCuenta.setText("Mostrar Pedido");
        BtnMostrarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMostrarCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(BtnMostrarCuenta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(LabelCuentaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 1018, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(LabelCuentaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnMostrarCuenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnMostrarCuenta.getAccessibleContext().setAccessibleName("hola");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMostrarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMostrarCuentaActionPerformed
        // TODO add your handling code here:
        String Total="";
        //Comidas
        if(comidaclase.getEnterodeQueso()>=1){
           Total+="precio unitario de dedos de queso 80  precio total:"+(comidaclase.getEnterodeQueso()*80)+"\n";
        }
        if(comidaclase.getAlitas() >0){
            Total+= "precio unitario de alitas 100 precio total: "+(comidaclase.getAlitas()*100)+ "\n";
        }
        if(comidaclase.getBurritos() >0){
            Total+="precio unitario de burritos 100 precio total: "+(comidaclase.getBurritos()*100)+ "\n";
            
        }
        if(comidaclase.getCorte() >0){
            Total+="precio unitario decorte 400 precio total: "+(comidaclase.getCorte()*400)+ "\n";  
        }
        if(comidaclase.getCostillas() >0){
            Total+="precio unitario de costillas 150 precio total: "+(comidaclase.getCostillas()*150)+ "\n";            
        }
        
        if(comidaclase.getPapas() >0){
            Total+="precio unitario de papas 100 precio total"+(comidaclase.getPapas()*100)+"\n";
        }
        if(comidaclase.getHamburguesa() >0){
            Total+="precio unitario de hamburguesa 100 precio total: "+(comidaclase.getHamburguesa()*100)+ "\n";
        }
        if(comidaclase.getHotdog()>0){
            Total+="precio unitario de hotdog 50 precio total: "+(comidaclase.getHotdog()*100)+ "\n";
        }
       if(comidaclase.getNachos()>0){
            Total+="precio unitario de nachos 50 precio total: "+(comidaclase.getNachos()*50)+ "\n";
            
        }
       if(comidaclase.getPizza()>0){
            Total+="precio unitario de pizzas 150 precio total: "+(comidaclase.getPizza()*150)+ "\n";
        }
       //Postres
       if(clasepostres.getflan()>0){
            Total+="precio unitario de flan 40 precio total: "+(clasepostres.getflan()*40)+ "\n";
        }
       if(clasepostres.getchocoflan()>0){
            Total+="precio unitario de chocoflan 40 precio total: "+(clasepostres.getflan()*40)+ "\n";
        }
       if(clasepostres.getconoHelado()>0){
            Total+="precio unitario de cono de helado 40 precio total: "+(clasepostres.getconoHelado()*40)+ "\n";
        }
       if(clasepostres.getpayDeLimon()>0){
           Total+="precio unitario de rebanada de pay de limon 40 precio total: "+(clasepostres.getpayDeLimon()*40)+ "\n";
        }
        if(clasepostres.getjericaya()>0){
           Total+="precio unitario de jericaya 40 precio total: "+(clasepostres.getjericaya()*40)+ "\n";
        }
        //Bebidas
        if(bebidasclase.getAguaLimon() > 0){
            Total+="precio unitario  de agua de limon 20$ precio total"+(bebidasclase.getAguaLimon()*20)+"\n";
        }
        if(bebidasclase.getCoca() > 0){
            Total+="precio unitario de coca cola 20$ precio total"+(bebidasclase.getCoca()*20)+"\n";
        }
        if(bebidasclase.getAguaNaranja()> 0){
            Total+="precio unitario de agua de naranja 20$ precio total"+(bebidasclase.getAguaNaranja()*20)+"\n";
        }
        if(bebidasclase.getClericot()>0){
            Total+= "Precio unatario de clericot 100$ precio total"+(bebidasclase.getClericot()*100)+"\n";
        }
       
        LabelCuentaTotal.setText(Total);
        
        
       
    }//GEN-LAST:event_BtnMostrarCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pagar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pagar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMostrarCuenta;
    private javax.swing.JLabel LabelCuentaTotal;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
